name: Gerar e Publicar Artigo

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install crewai==0.28.8 crewai_tools==0.1.6 langchain_community==0.0.29 openai requests
          pip install git+https://github.com/ClebertCode/serperdev.git

      - name: Executar script de geração
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python gerar
